---
title: "Looking at protein specific correlations"
output: html_document
date: "2025-06-13"
---

```{r source}
library(tidyverse)
library(ggrepel)

correlation_file <- read.csv('/Volumes/Calvin/TissueCrosstalk/Tissue_Pairs/Adipose - Subcutaneous_to_Heart - Left Ventricle/Correlation_results.csv')
```

```{r Filter: LGALS3}
LGALS3_list <- correlation_file %>%
  filter(grepl(",\\s*.+$", Target_gene),
         Source_gene == "Source_LGALS3") %>%
  arrange(desc(abs(r_correlation))) %>%
  mutate(rank = row_number(),
         `-ln(p)` = -log(p_adjusted + 1e-10),
         Source_gene = gsub("Source_", "", Source_gene),
         Target_gene = gsub("Target_","LV_", Target_gene))
LGALS3_select <- c(1,4,8)
LGALS3_select_df <- LGALS3_list[c(1,4,8), ]
#write.csv(x = LGALS3_list[1:20, ], "LGALS3_top20.csv", row.names = F)
```

```{r Filter: THPO}
THPO_list <- correlation_file %>%
  filter(grepl(",\\s*.+$", Target_gene),
         Source_gene == "Source_THPO") %>%
  arrange(desc(abs(r_correlation))) %>%
  mutate(rank = row_number(),
         `-ln(p)` = -log(p_adjusted + 1e-10),
         Source_gene = gsub("Source_", "", Source_gene),
         Target_gene = gsub("Target_", "LV_", Target_gene))
THPO_select <- c(1,4,7)
#write.csv(x = THPO_list[1:20, ], "THPO_top20.csv", row.names = F)
```

```{r Correlation plot overview: LGALS3}

LGALS3_main <- ggplot(data = LGALS3_list,
            mapping = aes(x = rank, y = `-ln(p)`)) +
  labs(#title = paste0(select_correlation$Source_gene[1], ":\nAdipose(Subcutaneous) ~ Heart(Left Ventricle)"),
       title = paste0( "LGALS3:\nAdipose(Subcutaneous) ~ Heart(Left Ventricle)"),
       x = "rank",
       y = "-ln(p)") +
  geom_hline(yintercept = -log(0.05), 
             color = 'black', 
             alpha = 0.25,
             linewidth = 1,
             linetype = "dashed") +
  geom_point(size = 1, 
             alpha = 0.2) +
  geom_point(data = LGALS3_list[LGALS3_select, ],
             #data = select_correlation[c(21, 85, 136), ],
             aes(color = Target_gene),
             size = 2,
             alpha = 0.7,
             color = c("blue", "violet", "red")) +
#  geom_text_repel(data = LGALS3_list[LGALS3_select, ],
#                  #data = select_correlation[c(21, 85, 136), ],
#                  aes(label = Target_gene),
#                  size = 2.5,
#                  box.padding = 0.5,
##                  point.padding = 5,
#                  nudge_x = 100,
#                  nudge_y = 0, 
#                  segment.color = "black",
#                  fontface = 'bold') +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.line = element_line(color = "black"),
        panel.background = element_blank(),
        panel.grid = element_blank(), 
        aspect.ratio = 0.619
  )

LGALS3_inset <- ggplot(data = LGALS3_list, mapping = aes(x = rank, y = `-ln(p)`)) +
  geom_point(size = 1, alpha = 0.5, color = 'black') +
  scale_x_continuous(limits = c(0, 50), 
                     breaks = seq(0, 50, 10)
                     ) +
  scale_y_continuous(limits = c(LGALS3_list$`-ln(p)`[1] - 5, LGALS3_list$`-ln(p)`[1] + 5), 
                     breaks = seq(
                       ceiling(round(LGALS3_list$`-ln(p)`[1] - 5, 8)), 
                       ceiling(round(LGALS3_list$`-ln(p)`[1] + 5, 8)), 
                       2)
                     ) +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.text.x = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 8, color = "black"),
        axis.title.x = element_text(size = 8, color = "black")) +
  geom_point(data = LGALS3_list[LGALS3_select, ],
             #data = select_correlation[c(21, 85, 136), ],
             aes(color = Target_gene),
             size = 2,
             alpha = 0.7,
             color = c("blue", "violet", "red")) 
#  geom_text_repel(data = LGALS3_list[LGALS3_select, ],
#                #data = select_correlation[c(21, 85, 136), ],
#                aes(label = Target_gene),
#                size = 2.5,
#                box.padding = 3,
#                segment.color = "black",
#                fontface = 'bold') 

combined <- LGALS3_main + annotation_custom(ggplotGrob(LGALS3_inset), xmin = 250, xmax = 550, ymin = 5, ymax = 20)
print(combined)
#print(LGALS3_main)
#print(LGALS3_inset)
#ggsave(filename = "LGALS3_Adipose-Heart_inset.pdf", plot = combined, dpi = 300)

```
```{r Correlation plot overview: THPO}

THPO_main <- ggplot(data = THPO_list,
            mapping = aes(x = rank, y = `-ln(p)`)) +
  labs(#title = paste0(select_correlation$Source_gene[1], ":\nAdipose(Subcutaneous) ~ Heart(Left Ventricle)"),
       title = paste0( "THPO:\nAdipose(Subcutaneous) ~ Heart(Left Ventricle)"),
       x = "rank",
       y = "-ln(p)") +
  geom_hline(yintercept = -log(0.05), 
             color = 'black', 
             alpha = 0.25,
             linewidth = 1,
             linetype = "dashed") +
  geom_point(size = 1, 
             alpha = 0.2) +
  geom_point(data = THPO_list[THPO_select, ],
             #data = select_correlation[c(21, 85, 136), ],
             aes(color = Target_gene),
             size = 2,
             alpha = 0.7,
             color = c("blue", "violet", "red")) +
#  geom_text_repel(data = THPO_list[THPO_select, ],
#                  #data = select_correlation[c(21, 85, 136), ],
#                  aes(label = Target_gene),
#                  size = 2.5,
#                  box.padding = 0.5,
##                  point.padding = 5,
#                  nudge_x = 100,
#                  nudge_y = 0, 
#                  segment.color = "black",
#                  fontface = 'bold') +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.line = element_line(color = "black"),
        panel.background = element_blank(),
        panel.grid = element_blank(), 
        aspect.ratio = 0.619
  )

THPO_inset <- ggplot(data = THPO_list, mapping = aes(x = rank, y = `-ln(p)`)) +
  geom_point(size = 1, alpha = 0.5, color = 'black') +
  scale_x_continuous(limits = c(0, 50), 
                     breaks = seq(0, 50, 10)
                     ) +
  scale_y_continuous(limits = c(THPO_list$`-ln(p)`[1] - 5, THPO_list$`-ln(p)`[1] + 5), 
                     breaks = seq(
                       ceiling(round(THPO_list$`-ln(p)`[1] - 5, 8)), 
                       ceiling(round(THPO_list$`-ln(p)`[1] + 5, 8)), 
                       2)
                     ) +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.text.x = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 8, color = "black"),
        axis.title.x = element_text(size = 8, color = "black")) +
  geom_point(data = THPO_list[THPO_select, ],
             #data = select_correlation[c(21, 85, 136), ],
             aes(color = Target_gene),
             size = 2,
             alpha = 0.7,
             color = c("blue", "violet", "red")) 
#  geom_text_repel(data = THPO_list[THPO_select, ],
#                #data = select_correlation[c(21, 85, 136), ],
#                aes(label = Target_gene),
#                size = 2.5,
#                box.padding = 3,
#                segment.color = "black",
#                fontface = 'bold') 

combined <- THPO_main + annotation_custom(ggplotGrob(THPO_inset), xmin = 250, xmax = 550, ymin = 5, ymax = 20)
print(combined)
print(THPO_main)
print(THPO_inset)
#ggsave(filename = "THPO_Adipose-Heart_inset.pdf", plot = combined, dpi = 300)

```
